worker_processes auto;

events {
  worker_connections 2048;
  multi_accept on;
}

http {
  # Enable Gzip compression for static assets
  gzip on;
  gzip_comp_level 5;
  gzip_min_length 256;
  gzip_proxied any;
  gzip_types
    application/javascript
    application/json
    application/x-javascript
    text/css
    text/javascript
    text/plain
    text/xml
    image/svg+xml;

  # Upstream application server pool with keepalive connection reuse
  upstream app_servers {
    server ctfd:8000;
    keepalive 32;
  }

  server {
    listen 80;
    client_max_body_size 4G;

    # Handle Server Sent Events for Notifications
    location /events {
      proxy_pass http://app_servers;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      chunked_transfer_encoding off;
      proxy_buffering off;
      proxy_cache off;
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
      proxy_set_header X-Forwarded-Prefix "";
    }

    # Proxy connections to the application servers with HTTP 1.1 keepalive
    location / {
      proxy_pass http://app_servers;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
      proxy_set_header X-Forwarded-Prefix "";
    }
  }
}

